name: 'Rust Auto Version Bumper'
description: "Automatically bump rust crate's changelog version based upon conventional commits."
inputs:
  token:  # github secret for pushing changes to repo
    description: 'Github Action access token for creating a version bump PR automatically. This should be a personal access token, and _not_ the standard secret token (which cannot push/trigger other actions, such as release steps on tag eg). But also different to any token needed for automatic merging of PRs...'
    required: true

runs:
  using: 'node12'
  main: 'index.js'
